### ISSUE TITLE
mac OS 10.13.2 and CUDA 8

### ISSUE THREAD

**Issue by helloniklas** [marnovo/macOS-eGPU-CUDA-guide#5]
So these instructions work great. However, on my macOS 10.13.2 CUDA 8 does not seem to work, while CUDA 9 does work. However, all the current deep learning frameworks, MXNET, tensor flow only support CUDA 8.

Did you ever upgrade this to 10.13.2 and still use CUDA 8?

**Comment by marnovo** [comment]
Hi @helloniklas, I haven't yet upgraded macOS to 10.13.2 as so far I didn't feel it was a safe bet. So far running macOS 10.13.1 and CUDA 8.

It is a rather tricky setup, particularly until Apple and NVIDIA befriend again. Effectively, this means you're unlikely to be able to run the latest version of everything—and eventually of anything.

I guess I could provide the suggested "latest guaranteed working" versions of macOS, Xcode, NVIDIA drivers and CUDA (and maybe even cuDNN), but it would get outdated rather frequently. So far I have the notice below to warn about it:

> As a rule-of-thumb, mind your macOS, Xcode, NVIDIA drivers and CUDA versions and always research before updating any of them.

Have you tried to compile any of the frameworks you are using from the source in your computer? It's far from guaranteed, but I have seen people get lucky with these in the past. Not very quick or straightforward, though.

**Comment by marnovo** [comment]
Follow-up:

Are you sure mxnet is not compatible with CUDA 9? Their release 0.12.0 release tells so: https://github.com/apache/incubator-mxnet/releases/tag/0.12.0

As for Tensorflow, luckily they released 1.5 a few days ago, which supports CUDA 9 (at last): https://github.com/tensorflow/tensorflow/releases/tag/v1.5.0-rc0

PyTorch, AFAIK, supports CUDA 9 for a while already.

This topic is also very helpful in matters related to macOS and CUDA compatibilities:
https://devtalk.nvidia.com/default/topic/1025945/mac-cuda-9-0-driver-fully-compatible-with-macos-high-sierra-10-13-error-quot-update-required-quot-solved-/

**Comment by helloniklas** [comment]
@marnovo yes, I was able the other week to successfully install Cuda 9 and cuDNN 7 on macOS 10.13.2 and then compile MXNET 1.0.1 from source. It all runs blazingly fast now on a Sonnett eGPU box with a Geforce 1080 card. If someone is interested see some steps here https://github.com/apache/incubator-mxnet/issues/9217

Apple's Turi will also supper CUDA 9 in their next release.

**Comment by marnovo** [comment]
That's very good news. Thanks for sharing the necessary steps! Will update the readme with some extra info on this.
